services:
  jph:
    build: .
    container_name: jph
    env_file: .env
    ports:
      - "8000:8000"
    environment:
      # кто админ в JupyterHub
      JPH_ADMIN_USER: "admin"

      # пароль для DummyAuthenticator
      JPH_DUMMY_PASSWORD: "${JPH_DUMMY_PASSWORD}"

      # сеть докера, где будут жить singleuser контейнеры
      DOCKER_NETWORK_NAME: "jphub"

      # образ singleuser (JupyterLab)
      DOCKER_NOTEBOOK_IMAGE: "jupyterhub/singleuser"
      DOCKER_NOTEBOOK_DIR: "/home/jovyan"
      DOCKER_SPAWN_CMD: "start-singleuser.sh"
    volumes:
      # конфиг JupyterHub (меняем без пересборки)
      - ./data/jph/jupyterhub_config.py:/app/jupyterhub_config.py:ro

      # данные JupyterHub: cookie_secret, sqlite DB, pid proxy
      - ./data/jph:/data

      # чтобы DockerSpawner мог запускать пользовательские контейнеры
      - /var/run/docker.sock:/var/run/docker.sock:rw
    networks:
      - jphub
    command: >
      sh -c "python -m jupyterhub --config /app/jupyterhub_config.py --upgrade-db"

networks:
  jphub:
    name: jphub
